# Config definition
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# 1.Data General Setting. Can be replaced in respective sets
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
DATA:
 DATASETS:
  NAMES: ('ddr_DRgrading')
  ROOT_DIR: ('./data')

 DATALOADER:
  NUM_WORKERS: 1
  SAMPLER: 'softmax_rank'#'ranked_loss'#
  CATEGORIES_PER_BATCH: 6
  INSTANCES_PER_CATEGORY_IN_BATCH: 4
  IMS_PER_BATCH: 24

 TRANSFORM:
  SIZE: [300,300]#[512, 512]
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  PADDING: 10

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# 2.Model General Setting. Can be replaced in respective sets Structure Information
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
MODEL:
 DEVICE: "cuda"
 #DEVICE_ID: '0'
 NAME: 'resnet50_ibn_a'
 STN: 'no'
 LAST_STRIDE: 1

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# 3.LOSS General Setting. Can be replaced in respective sets Structure Information
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
LOSS:
 TYPE: 'similarity_loss'
 MARGIN_RANK: 1.3 ### R: ALPHA - MARGIN_RANK
 ALPHA: 2.0
 TVAL: 1.0
 WEIGHT: 0.4    ### loss: softmax + w*ranked_loss


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# 4.Solver
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
SOLVER:
 MAX_EPOCHS: 50
 EVAL_PERIOD: 5
 CHECKPOINT_PERIOD: 5
 LOG_PERIOD: 10
 OUTPUT_DIR: "work_space" 

 # OPTIMIZER configuration
 OPTIMIZER:
  NAME: "Adam"
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.

 # SCHEDULER configuration
 SCHEDULER:
  BASE_LR: 0.0035
  BIAS_LR_FACTOR: 1
  GAMMA: 0.1
  STEPS: [6,8]#[2, 4]  
  WARMUP_FACTOR: 0.33
  WARMUP_ITERS: 0
  WARMUP_METHOD: "linear"
  RETRAIN_FROM_HEAD: 1


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Specific Setting - Train Configuration
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
TRAIN:
 RE_RANKING: 'no'
 WEIGHT: ""
 FEAT_NORM: 'yes'

 # Train Transform
 TRANSFORM:
  PROB: 0.0
  RE_PROB: 0.0

 # Train Dataloader
 DATALOADER:
  CATEGORIES_PER_BATCH: 6
  INSTANCES_PER_CATEGORY_IN_BATCH: 6#2

 # Train Trick
 TRICK:
  PRETRAIN_PATH: r'D:\Research\MIP\Experiment\RLL\modeling\resnet50_ibn_a.pth.tar'#'D:/Research/MIP/Experiment/RLL/work_space/pre/resnet50_ibn_a_model_30.pth'  
  IF_LABELSMOOTH: 'on'


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Specific Setting - Val Configuration
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
VAL:
 RE_RANKING: 'no'
 WEIGHT: ""
 FEAT_NORM: 'yes'

 # Val Dataloader
 DATALOADER:
  CATEGORIES_PER_BATCH: 6
  INSTANCES_PER_CATEGORY_IN_BATCH: 4#1

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Specific Setting - Test Configuration
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
TEST:
 RE_RANKING: 'no'
 WEIGHT: "D:/Research/MIP/Experiment/RLL/work_space/resnet50_ibn_a_model_21.pth"
 FEAT_NORM: 'yes'

 # Test Dataloader
 DATALOADER:
  CATEGORIES_PER_BATCH: 6
  INSTANCES_PER_CATEGORY_IN_BATCH: 4#3