MODEL:
  PRETRAIN_CHOICE: 'imagenet'  ## imagenet
  PRETRAIN_PATH: 'modeling/resnet50_ibn_a.pth.tar'
  METRIC_LOSS_TYPE: 'ranked_loss'
  IF_LABELSMOOTH: 'on'

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  NAMES: ('dukemtmc') ### dukemtmc , market1501

DATALOADER:
  SAMPLER: 'softmax_rank'
  NUM_INSTANCE: 4
  NUM_WORKERS: 4

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 120
  BASE_LR: 0.00035

  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [40, 70]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 20
  EVAL_PERIOD: 80

TEST:
  IMS_PER_BATCH: 32
  RE_RANKING: 'no'
  WEIGHT: "path"
  FEAT_NORM: 'yes'

OUTPUT_DIR: "work_space"


