MODEL:
  PRETRAIN_CHOICE: 'self'# imagenet# 'self' 
  PRETRAIN_PATH: 'D:/Research/MIP/Experiment/RLL/work_space/pre/resnet50_ibn_a_model_30.pth'
  #'D:/Research/MIP/Experiment/RLL/work_space/pre/resnet50_ibn_a_model_30.pth'
  #'modeling/resnet50_ibn_a.pth.tar'
  METRIC_LOSS_TYPE: 'ranked_loss'
  #IF_LABELSMOOTH: 'on'

INPUT:
  SIZE_TRAIN: [300, 300]
  SIZE_TEST: [300, 300]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  NAMES: ('fundusTR')###('dukemtmc') ### dukemtmc , market1501

DATALOADER:
  SAMPLER: 'softmax_rank'
  NUM_INSTANCE: 2
  NUM_WORKERS: 1

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 30
  BASE_LR: 0.035

  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 24

  STEPS: [10, 20]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 10  #40
  EVAL_PERIOD: 1

TRAIN:
  CATEGORIES_PER_BATCH: 2  #6
  INSTANCES_PER_CATEGORY_IN_BATCH: 8  #6
  IMS_PER_BATCH: 16
  RE_RANKING: 'no'
  WEIGHT: "path"
  FEAT_NORM: 'yes'

VAL:
  CATEGORIES_PER_BATCH: 2  #6
  INSTANCES_PER_CATEGORY_IN_BATCH: 8  #6
  IMS_PER_BATCH: 16
  RE_RANKING: 'no'
  WEIGHT: "path"
  FEAT_NORM: 'yes'

TEST:
  CATEGORIES_PER_BATCH: 2   #6
  INSTANCES_PER_CATEGORY_IN_BATCH: 8  #4
  IMS_PER_BATCH: 16
  RE_RANKING: 'no'
  WEIGHT: "path"
  FEAT_NORM: 'yes'

OUTPUT_DIR: "work_space"


